services:
  app:
    build: .
    container_name: assesment-wpp-api
    restart: unless-stopped
    env_file: .env
    environment:
      - TZ=Asia/Jakarta
    depends_on:
      - db
    networks:
      - proxy-network
      - assesment-internal

  db:
    image: mysql:8.0
    container_name: assesment-wpp-db
    command: --skip-name-resolve --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "127.0.0.1:3308:3306" # <-- Diubah ke 3308 karena 3307 sudah dipakai kavling
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Jakarta
    volumes:
      - assesment_db_data:/var/lib/mysql
    networks:
      - assesment-internal

networks:
  proxy-network:
    external: true
  assesment-internal:
    driver: bridge

volumes:
  assesment_db_data:
