services:
  app:
    build: .
    container_name: assesment-wpp-api
    restart: unless-stopped
    env_file: .env
    environment:
      - TZ=Asia/Jakarta
    depends_on:
      - db
    networks:
      - proxy-network
      - assesment-internal

  db:
    image: postgres:15-alpine
    container_name: assesment-wpp-db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Jakarta
    volumes:
      - assesment_db_data:/var/lib/postgresql/data
    networks:
      - assesment-internal

networks:
  proxy-network:
    external: true
  assesment-internal:
    driver: bridge
# test trigger ci 8
volumes:
  assesment_db_data:
