name: Continuous Deployment Backend
on:
  push:
    branches: ["main"]
    paths:
      - "server/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ke Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/apps/assesment-wpp
            git pull origin main
            cd server
            cat <<EOT > .env
            PORT=3000
            NODE_ENV=production
            DATABASE_URL="mysql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@assesment-wpp-db:3306/${{ secrets.DB_NAME }}"
            CORS_ORIGINS="${{ secrets.CORS_ORIGINS }}"
            GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}"
            DB_USER="${{ secrets.DB_USER }}"
            DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
            DB_NAME="${{ secrets.DB_NAME }}"
            EOT
            docker compose up -d --build
            docker compose exec -T app npx prisma db push
            docker compose exec -T app npm run seed
            docker image prune -af
